export const transactionData = [
    {
      customerID: 1,
      name: "Tom",
      transactionDt: "06-01-2020",
      amountSpent: '$120',
      
    },
    {
      customerID: 1,
      name: "Tom",
      transactionDt: "06-12-2020",
      amountSpent: '$70',
    },
    {
      customerID: 1,
      name: "Tom",
      transactionDt: "06-12-2020",
      amountSpent: '$95',
    },
    {
      customerID: 1,
      name: "Tom",
      transactionDt: "07-05-2020",
      amountSpent: '$80',
    },
    {
      customerID: 1,
      name: "Tom",
      transactionDt: "07-06-2020",
      amountSpent: '$225',
    },
    {
      customerID: 1,
      name: "Tom",
      transactionDt: "08-4-2020",
      amountSpent: '$150',
    },
    {
      customerID: 1,
      name: "Tom",
      transactionDt: "08-14-2020",
      amountSpent: '$162',
    },
    {
      customerID: 1,
      name: "Tom",
      transactionDt: "07-24-2020",
      amountSpent: '$122',
    },
    {
      customerID: 2,
      name: "Nick",
      amountSpent: '$125',
      transactionDt: "06-12-2020",
    },
    {
      customerID: 2,
      name: "Nick",
      amountSpent: '$13',
      transactionDt: "07-14-2020",
    },
    {
      customerID: 2,
      name: "Nick",
      amountSpent: '$225',
      transactionDt: "08-7-2020",
    },
    {
      customerID: 3,
      name: "Michael",
      transactionDt: "06-12-2020",
      amountSpent: '$125',
    },
    {
      customerID: 3,
      name: "Michael",
      transactionDt: "07-12-2020",
      amountSpent: '$75',
    },
    {
      customerID: 3,
      name: "Michael",
      transactionDt: "06-13-2020",
      amountSpent: '$194',
    },
    {
      customerID: 3,
      name: "Michael",
      transactionDt: "07-13-2020",
      amountSpent: '$200',
    },
    {
      customerID: 3,
      name: "Michael",
      transactionDt: "08-13-2020",
      amountSpent: '$156',
    },
    {
      customerID: 4,
      name: "Max",
      transactionDt: "06-12-2020",
      amountSpent: '$120',
    },
    {
      customerID: 4,
      name: "Max",
      transactionDt: "06-21-2020",
      amountSpent: '$210',
    },
    {
      customerID: 4,
      name: "Max",
      transactionDt: "07-13-2020",
      amountSpent: '$140',
    },
    {
      customerID: 4,
      name: "Max",
      transactionDt: "07-14-2020",
      amountSpent: '$110',
    },
    {
      customerID: 4,
      name: "Max",
      transactionDt: "08-13-2020",
      amountSpent: '$165',
    },
    {
      customerID: 4,
      name: "Max",
      transactionDt: "07-12-2020",
      amountSpent: '$220',
    },
    {
      customerID: 5,
      name: "Jake",
      transactionDt: "06-13-2020",
      amountSpent: '$50',
    },
    {
      customerID: 5,
      name: "Jake",
      transactionDt: "07-12-2020",
      amountSpent: '$55',
    },
    {
      customerID: 5,
      name: "Jake",
      transactionDt: "08-13-2020",
      amountSpent: '$100',
    },
    {
      customerID: 6,
      name: "Steve",
      transactionDt: "06-12-2020",
      amountSpent: '$101',
    },
    {
      customerID: 6,
      name: "Steve",
      transactionDt: "07-12-2020",
      amountSpent: '$220',
    },
    {
      customerID: 6,
      name: "Steve",
      transactionDt: "08-12-2020",
      amountSpent: '$100',
    },
    {
      customerID: 7,
      name: "Milli",
      transactionDt: "06-12-2020",
      amountSpent: '$50',
    },
    {
      customerID: 7,
      name: "Milli",
      transactionDt: "07-12-2020",
      amountSpent: '$99',
    },
    {
      customerID: 7,
      name: "Milli",
      transactionDt: "08-12-2020",
      amountSpent: '$49'
    }
  ];
  